### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by RenijS** [Renji-and-frens/meal-planner-frontend#12]
We need to implement a Navbar component for our website. The Navbar is our main navigation menu.

Requirements:

- Create NavBar component file, i.e., NavBar.jsx.
- The Navbar should adapt to different screen sizes.
- It should include navigation links for essential pages such as Home, Recipes, Meal Planner, Saved Items, About, and Contact.

Please don't worry about color for now.

Big screen:

![Image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/69236889/d53c2cb6-b6de-45ce-8196-0f84dd733a8d)

Small screen:

![Image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/69236889/a75956b9-9629-4009-919c-7cf03846abcd)

**Comment by Skipper-kenya** [comment]
Assign me this

**Comment by Skipper-kenya** [comment]
could you please check if the setup is correct. after running npm install and npm start i'm still getting an error

**Comment by RenijS** [comment]
v1 completed
