### ISSUE TITLE
Initial commit - frontend initial barebone setups

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-frontend#2]
The initial commit of the repo!
@RenijS will be the one who makes the commit with the project fully set up, ready for development.

- [ ] Project initial files created and can compile, defaulting to a blank landing page.
- [ ] README.md with steps on how to install required packages, tools, and how to run the project on local env.

**Comment by RenijS** [comment]
This has been completed so closing it.
