### ISSUE TITLE
Create search bar component

### ISSUE THREAD

**Issue by RenijS** [Renji-and-frens/meal-planner-frontend#20]
We need to implement recipe search bar component.

Requirements:

- Create search bar file in components folder, for example - SearchBar.jsx
- Implement the design to code.

![Image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/69236889/aa042864-3d43-49d2-8302-ff744810bedc)

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to work on the issue
