### ISSUE TITLE
Profanity filter

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-frontend#21]
Implement a profanity filter for any text-based fields that would submit data to the backend. Preferably regex since it's quick. Open for discussion. (plz don't go too crazy with the profanities in this issue lmao, put it in a link or something and then post the link so others don't accidentally stumble upon thousands of random profanity word list)
https://stackoverflow.com/questions/273516/how-do-you-implement-a-good-profanity-filter

**Comment by RenijS** [comment]
Hey @yuuni-mikawane, I have merged profanity filter code to the main branch. Do test it on the live server and let me know any changes needs to be made.
