### ISSUE TITLE
Implement Flexible Button Component

### ISSUE THREAD

**Issue by RenijS** [Renji-and-frens/meal-planner-frontend#24]
We need to create a flexible button component that adapts to different titles and color schemes based on our design requirements. The button component should be reusable across the website and easily customizable.

![Image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/69236889/158dd326-3c62-4a94-a577-2fd4593b1743)

Requirements:

- Create a new button component file, for example, Button.jsx, in the components folder.
- The button should be flexible in terms of its title, allowing us to pass any text content as a prop.
- Implement styling options to customize the button's appearance, including background color, text color, hover effects, and border styles.
- Design the button component to be reusable across different sections of the website, maintaining consistency in appearance and behavior.

Let me know if you need further clarification or have any questions!

**Comment by GeorgiosDrivas** [comment]
Hello! To recap, you need a Button Component with customization options such as:

- text color
- Background color
- Hover Effects
- Border radius / Border

You also want to have the option to change the button's title by passing it as a prop to the component as well.

If I understand correctly, I would like to work on this issue.

**Comment by Vishalvirdi** [comment]
Hey, Can u please assign issue to me. I would love to contribute.
