### ISSUE TITLE
Possible bug/annoyance with hidden quick links navbar 

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-frontend#30]
Hey @RenijS , can you please confirm about this current "feature" on homepage:
When user move mouse from the navbar and downwards, past the navbar bottom border, a hidden quick links view is displayed automatically? This seems to be quite annoying and I personally find it an unintentional feature.
Should we improve it? Maybe by having a new dedicated button on main navbar for displaying that (on hover or on click)?

If this is intended, can you give me a quick run through of why it's like this xD

If needed, go ahead and assign this task to someone in @Renji-and-frens/mp-frontend team. Would be a good exercise.

tysm

**Comment by RenijS** [comment]
Yeah, it's a bug. I believe I have got a solution to it, I'll look into it in my free time. Thanks
