### ISSUE TITLE
Homepage - some image elements load really slowly, both on refresh and on site visit

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-frontend#31]
![image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/62007628/543ad0d0-5143-4387-97aa-d69a4c50daa4)
This part to be specific. Would need to optimize these elements to make things run smoother. Something like:

- Reduced file size for lighter load
- Hide when load starts, fade in when fully loaded - this is for masking the loading operation and give it a nice animation that would not annoy users

@RenijS feel free to assign anyone in @Renji-and-frens/mp-frontend team, would be a cool optimizing task. Of course, put out any ideas you have!

**Comment by RenijS** [comment]
Hey @yuuni-mikawane,
I have uploaded a new code regarding this, what do you think about the loading style? Any suggestions or all good for now?

**Comment by yuuni-mikawane** [comment]
> Hey @yuuni-mikawane, I have uploaded a new code regarding this, what do you think about the loading style? Any suggestions or all good for now?

Looks good to me - probably some fading animation would make it look even smoother.
But for now it's already a lot better than before. Tysm.
Btw can you link the commit with the issue by adding `#<issue number>` at the start of the commit message from now on? For ease of access
