### ISSUE TITLE
Login Form coding

### ISSUE THREAD

**Issue by RenijS** [Renji-and-frens/meal-planner-frontend#7]
Login form creation for Login Page. Create separate component for login form, (folder path: src > components > form > LoginForm.jsx).

Items:- email, password, forgot password, sign in button and sign up. 

![Image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/69236889/5751f98b-17d6-4a1f-90e4-0fedb0b001ab)

**Comment by RenijS** [comment]
Not ready to be picked. After we finalise design.

**Comment by DanNgo4** [comment]
hi @RenijS, can I use material UI to implement this component in the login form?
![image](https://github.com/Renji-and-frens/meal-planner-frontend/assets/127183060/484bc4bc-6f0d-4d97-b46d-9b566cc31b3b)

**Comment by RenijS** [comment]
Hey @DanNgo4 ,

Sorry for late reply, didn't see the comment. Yes, feel free to use anything as long as you don't break the project. :)
